### ISSUE TITLE
Missing 'connect/send' module

### ISSUE THREAD

**Issue by roytruelove** [shovon/grunt-harp#20]
```
$ grunt -version
grunt-cli v1.2.0
grunt v1.0.1

$ cat package.json | grep grunt-harp
    "grunt-harp": "^0.18.0-0.0.0",
```

Getting the following when trying to run `grunt harp`:

Error: Cannot find module '../node_modules/connect/node_modules/send'

Full stack:

```
Loading "harp.js" tasks...ERROR
>> Error: Cannot find module '../node_modules/connect/node_modules/send'
>>   at Function.Module._resolveFilename (module.js:339:15)
>>   at Function.Module._load (module.js:290:25)
>>   at Module.require (module.js:367:17)
>>   at require (internal/module.js:16:19)
>>   at Object.<anonymous> (/XXX/node_modules/grunt-harp/node_modules/harp/lib/middleware.js:10:12)
>>   at Module._compile (module.js:413:34)
>>   at Object.Module._extensions..js (module.js:422:10)
>>   at Module.load (/XXX/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:314:12)
>>   at Module.require (module.js:367:17)
>>   at require (internal/module.js:16:19)
>>   at Object.<anonymous> (/XXX/node_modules/grunt-harp/node_modules/harp/lib/index.js:8:19)
>>   at Module._compile (module.js:413:34)
>>   at Object.Module._extensions..js (module.js:422:10)
>>   at Module.load (/XXX/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:314:12)
>>   at Module.require (module.js:367:17)
>>   at require (internal/module.js:16:19)
>>   at Object.module.exports (/XXX/node_modules/grunt-harp/tasks/harp.js:13:14)
>>   at loadTask (/XXX/node_modules/grunt/lib/grunt/task.js:318:10)
>>   at /XXX/node_modules/grunt/lib/grunt/task.js:354:7
>>   at Array.forEach (native)
>>   at loadTasks (/XXX/node_modules/grunt/lib/grunt/task.js:353:11)
>>   at Task.task.loadNpmTasks (/XXX/node_modules/grunt/lib/grunt/task.js:401:5)
>>   at Object.module.exports (/XXX/Gruntfile.js:38:9)
>>   at loadTask (/XXX/node_modules/grunt/lib/grunt/task.js:318:10)
>>   at Task.task.init (/XXX/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (/XXX/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/XXX/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:413:34)
>>   at Object.Module._extensions..js (module.js:422:10)
>>   at Module.load (module.js:357:32)
>>   at Function.Module._load (module.js:314:12)
>>   at Function.Module.runMain (module.js:447:10)
>>   at startup (node.js:146:18)
>>   at node.js:404:3
Loading "Gruntfile.js" tasks...OK
```

**Comment by dwarcher** [comment]
I'm also having a similar problem on node v6.9.5. I noticed this plugin is using an older version of harp - would you mind updating to the latest (0.23)?
